global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'api'
    static_configs:
    - targets: ['api:9090']
  - job_name: 'postgresql'
    static_configs:
    - targets: ['pg_exporter:9187']
  - job_name: 'sender'
    static_configs:
    - targets: ['sender:9090']
  - job_name: 'scheduler'
    static_configs:
    - targets: ['scheduler:9090']
